-- Row-level security: the second layer of tenant isolation.
--
-- The application layer is the real defence — every query goes through
-- src/lib/db/scoped/* holding a BuildingContext. This is what catches the
-- mistake when someone routes around it.
--
-- Each request runs inside a transaction that issues
--   SET LOCAL app.current_building_id = '<uuid>'
-- A query that escapes that wrapper has no setting, the predicate evaluates to
-- NULL, and it returns zero rows. Fail closed, never fail open.
--
-- FORCE ROW LEVEL SECURITY matters as much as ENABLE: without it the table
-- owner is exempt, and an app connecting as the owner would have policies that
-- do exactly nothing.
--
-- Generated by scripts/generate-rls.ts. Regenerate after adding a tenant table.
-- 38 tenant tables.

-- AlterationRequest
ALTER TABLE "AlterationRequest" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AlterationRequest" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "AlterationRequest";
CREATE POLICY tenant_isolation ON "AlterationRequest"
  USING ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid)
  WITH CHECK ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid);

-- ApprovalComment
ALTER TABLE "ApprovalComment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ApprovalComment" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "ApprovalComment";
CREATE POLICY tenant_isolation ON "ApprovalComment"
  USING ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid)
  WITH CHECK ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid);

-- ApprovalRequest
ALTER TABLE "ApprovalRequest" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ApprovalRequest" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "ApprovalRequest";
CREATE POLICY tenant_isolation ON "ApprovalRequest"
  USING ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid)
  WITH CHECK ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid);

-- AuditLog
ALTER TABLE "AuditLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AuditLog" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "AuditLog";
CREATE POLICY tenant_isolation ON "AuditLog"
  USING ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid)
  WITH CHECK ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid);

-- Booking
ALTER TABLE "Booking" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Booking" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "Booking";
CREATE POLICY tenant_isolation ON "Booking"
  USING ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid)
  WITH CHECK ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid);

-- BookingPrerequisiteCheck
ALTER TABLE "BookingPrerequisiteCheck" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BookingPrerequisiteCheck" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "BookingPrerequisiteCheck";
CREATE POLICY tenant_isolation ON "BookingPrerequisiteCheck"
  USING ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid)
  WITH CHECK ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid);

-- Building
ALTER TABLE "Building" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Building" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "Building";
CREATE POLICY tenant_isolation ON "Building"
  USING ("id" = NULLIF(current_setting('app.current_building_id', true), '')::uuid)
  WITH CHECK ("id" = NULLIF(current_setting('app.current_building_id', true), '')::uuid);

-- BuildingDataLookup
ALTER TABLE "BuildingDataLookup" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BuildingDataLookup" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "BuildingDataLookup";
CREATE POLICY tenant_isolation ON "BuildingDataLookup"
  USING ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid)
  WITH CHECK ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid);

-- BuildingRuleAssessment
ALTER TABLE "BuildingRuleAssessment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BuildingRuleAssessment" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "BuildingRuleAssessment";
CREATE POLICY tenant_isolation ON "BuildingRuleAssessment"
  USING ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid)
  WITH CHECK ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid);

-- BuildingWork
ALTER TABLE "BuildingWork" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BuildingWork" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "BuildingWork";
CREATE POLICY tenant_isolation ON "BuildingWork"
  USING ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid)
  WITH CHECK ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid);

-- CertificateOfInsurance
ALTER TABLE "CertificateOfInsurance" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CertificateOfInsurance" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "CertificateOfInsurance";
CREATE POLICY tenant_isolation ON "CertificateOfInsurance"
  USING ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid)
  WITH CHECK ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid);

-- Charge
ALTER TABLE "Charge" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Charge" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "Charge";
CREATE POLICY tenant_isolation ON "Charge"
  USING ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid)
  WITH CHECK ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid);

-- Document
ALTER TABLE "Document" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Document" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "Document";
CREATE POLICY tenant_isolation ON "Document"
  USING ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid)
  WITH CHECK ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid);

-- DocumentLink
ALTER TABLE "DocumentLink" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DocumentLink" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "DocumentLink";
CREATE POLICY tenant_isolation ON "DocumentLink"
  USING ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid)
  WITH CHECK ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid);

-- DsnyFine
ALTER TABLE "DsnyFine" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DsnyFine" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "DsnyFine";
CREATE POLICY tenant_isolation ON "DsnyFine"
  USING ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid)
  WITH CHECK ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid);

-- DutyAssignment
ALTER TABLE "DutyAssignment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DutyAssignment" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "DutyAssignment";
CREATE POLICY tenant_isolation ON "DutyAssignment"
  USING ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid)
  WITH CHECK ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid);

-- DutyRotation
ALTER TABLE "DutyRotation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DutyRotation" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "DutyRotation";
CREATE POLICY tenant_isolation ON "DutyRotation"
  USING ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid)
  WITH CHECK ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid);

-- Invitation
ALTER TABLE "Invitation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Invitation" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "Invitation";
CREATE POLICY tenant_isolation ON "Invitation"
  USING ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid)
  WITH CHECK ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid);

-- Meeting
ALTER TABLE "Meeting" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Meeting" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "Meeting";
CREATE POLICY tenant_isolation ON "Meeting"
  USING ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid)
  WITH CHECK ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid);

-- MeetingAttendance
ALTER TABLE "MeetingAttendance" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MeetingAttendance" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "MeetingAttendance";
CREATE POLICY tenant_isolation ON "MeetingAttendance"
  USING ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid)
  WITH CHECK ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid);

-- Membership
ALTER TABLE "Membership" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Membership" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "Membership";
CREATE POLICY tenant_isolation ON "Membership"
  USING ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid)
  WITH CHECK ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid);

-- MembershipUnit
ALTER TABLE "MembershipUnit" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MembershipUnit" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "MembershipUnit";
CREATE POLICY tenant_isolation ON "MembershipUnit"
  USING ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid)
  WITH CHECK ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid);

-- NoticeCampaign
ALTER TABLE "NoticeCampaign" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "NoticeCampaign" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "NoticeCampaign";
CREATE POLICY tenant_isolation ON "NoticeCampaign"
  USING ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid)
  WITH CHECK ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid);

-- NoticeDelivery
ALTER TABLE "NoticeDelivery" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "NoticeDelivery" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "NoticeDelivery";
CREATE POLICY tenant_isolation ON "NoticeDelivery"
  USING ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid)
  WITH CHECK ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid);

-- Notification
ALTER TABLE "Notification" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Notification" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "Notification";
CREATE POLICY tenant_isolation ON "Notification"
  USING ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid)
  WITH CHECK ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid);

-- Obligation
ALTER TABLE "Obligation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Obligation" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "Obligation";
CREATE POLICY tenant_isolation ON "Obligation"
  USING ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid)
  WITH CHECK ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid);

-- ObligationReminder
ALTER TABLE "ObligationReminder" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ObligationReminder" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "ObligationReminder";
CREATE POLICY tenant_isolation ON "ObligationReminder"
  USING ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid)
  WITH CHECK ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid);

-- Payment
ALTER TABLE "Payment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Payment" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "Payment";
CREATE POLICY tenant_isolation ON "Payment"
  USING ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid)
  WITH CHECK ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid);

-- PaymentPlan
ALTER TABLE "PaymentPlan" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PaymentPlan" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "PaymentPlan";
CREATE POLICY tenant_isolation ON "PaymentPlan"
  USING ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid)
  WITH CHECK ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid);

-- Proxy
ALTER TABLE "Proxy" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Proxy" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "Proxy";
CREATE POLICY tenant_isolation ON "Proxy"
  USING ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid)
  WITH CHECK ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid);

-- Resolution
ALTER TABLE "Resolution" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Resolution" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "Resolution";
CREATE POLICY tenant_isolation ON "Resolution"
  USING ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid)
  WITH CHECK ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid);

-- Resource
ALTER TABLE "Resource" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Resource" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "Resource";
CREATE POLICY tenant_isolation ON "Resource"
  USING ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid)
  WITH CHECK ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid);

-- ResourcePrerequisite
ALTER TABLE "ResourcePrerequisite" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ResourcePrerequisite" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "ResourcePrerequisite";
CREATE POLICY tenant_isolation ON "ResourcePrerequisite"
  USING ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid)
  WITH CHECK ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid);

-- ShareAllocation
ALTER TABLE "ShareAllocation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ShareAllocation" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "ShareAllocation";
CREATE POLICY tenant_isolation ON "ShareAllocation"
  USING ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid)
  WITH CHECK ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid);

-- SubletRegistration
ALTER TABLE "SubletRegistration" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SubletRegistration" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "SubletRegistration";
CREATE POLICY tenant_isolation ON "SubletRegistration"
  USING ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid)
  WITH CHECK ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid);

-- Ticket
ALTER TABLE "Ticket" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Ticket" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "Ticket";
CREATE POLICY tenant_isolation ON "Ticket"
  USING ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid)
  WITH CHECK ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid);

-- Unit
ALTER TABLE "Unit" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Unit" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "Unit";
CREATE POLICY tenant_isolation ON "Unit"
  USING ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid)
  WITH CHECK ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid);

-- UnitHolding
ALTER TABLE "UnitHolding" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "UnitHolding" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "UnitHolding";
CREATE POLICY tenant_isolation ON "UnitHolding"
  USING ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid)
  WITH CHECK ("buildingId" = NULLIF(current_setting('app.current_building_id', true), '')::uuid);

-- Sign-in bootstrap.
--
-- src/lib/db/context.ts opens one transaction that sets app.current_user_id,
-- reads that user's own memberships, sets app.member_building_ids from the
-- result, and then reads those buildings. Nothing else in the application is
-- permitted to cross a tenant boundary.

-- A person can always read their own membership rows, in any building.
DROP POLICY IF EXISTS member_self ON "Membership";
CREATE POLICY member_self ON "Membership"
  FOR SELECT
  USING ("userId" = NULLIF(current_setting('app.current_user_id', true), '')::uuid);

-- A building is readable when the bootstrap step has already established, from
-- that user's own membership rows, that they belong to it.
DROP POLICY IF EXISTS member_bootstrap ON "Building";
CREATE POLICY member_bootstrap ON "Building"
  FOR SELECT
  USING (
    "id" = ANY(
      string_to_array(
        NULLIF(current_setting('app.member_building_ids', true), ''), ','
      )::uuid[]
    )
  );

-- Background jobs.
--
-- The daily reminder run must find work in every building, and the delivery
-- webhook arrives knowing a provider message id and nothing else. Both need to
-- answer "which building?" before any scoped work can start.
--
-- The grant is the smallest thing that answers it: reading the tenant registry
-- and reading notifications, both SELECT only. Everything else still requires
-- app.current_building_id, so a job resolves the building here and then does
-- its real work inside withBuildingTx.
DROP POLICY IF EXISTS job_building_scan ON "Building";
CREATE POLICY job_building_scan ON "Building"
  FOR SELECT
  USING (current_setting('app.job_scope', true) = 'all_buildings');

DROP POLICY IF EXISTS job_notification_scan ON "Notification";
CREATE POLICY job_notification_scan ON "Notification"
  FOR SELECT
  USING (current_setting('app.job_scope', true) = 'all_buildings');

-- Invitation redemption.
--
-- Someone following an invitation link has, by definition, no membership yet,
-- so there is no tenant to resolve and tenant_isolation would hide the row that
-- is about to grant them one.
--
-- The scope is one row wide: the policy matches on the token hash the caller
-- has already presented, so even a session that sets this setting sees only the
-- invitation it can already produce a token for. Enumerating invitations is not
-- possible, and neither is reading anything else in the building — the rest of
-- redemption happens inside withBuildingTx once the row names its building.
DROP POLICY IF EXISTS invitation_by_token ON "Invitation";
CREATE POLICY invitation_by_token ON "Invitation"
  FOR SELECT
  USING (
    "tokenHash" = NULLIF(current_setting('app.invitation_token_hash', true), '')
  );

-- Runtime role grants.
--
-- The app role owns nothing, so it needs explicit privileges. It is also never
-- granted UPDATE or DELETE on the append-only tables: a correction to the
-- ledger is a reversing entry, and an audit log that can be edited is not an
-- audit log.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'cooperator_app') THEN
    RAISE NOTICE 'Role cooperator_app does not exist; skipping grants. Run pnpm db:setup.';
    RETURN;
  END IF;

  EXECUTE 'GRANT USAGE ON SCHEMA public TO cooperator_app';
  EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO cooperator_app';
  EXECUTE 'GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO cooperator_app';

  EXECUTE 'REVOKE UPDATE, DELETE ON "AuditLog" FROM cooperator_app';
  EXECUTE 'REVOKE UPDATE, DELETE ON "Charge" FROM cooperator_app';
  EXECUTE 'REVOKE UPDATE, DELETE ON "Payment" FROM cooperator_app';

  EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO cooperator_app';
  EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO cooperator_app';
END
$$;
